### ISSUE TITLE
Faster implementation of functions

### ISSUE THREAD

**Issue by DominikRafacz** [BioGenies/tidysq#2]
Performance of most of the functions can still be improved by moving their work to C++. Below we will keep list of them:

Important (improvement gain is relatively big in comparison to workload):
* `%has%` operator,
* `==` operator (it uses `as.character` -- that can be inefficient; it doesn't even need to be written in C++).
* `encode`, `typify`, `substitute_letters` (checking for presence of unspecified letters in R is way too slow)
* `encsq_to_list`
* `write_fasta`
* `reverse`

More trickier (they require quite a lot work):
* `bite` (it could unpack sequences "intelligently" ),
* `clean`
* `complement`

**Comment by MatiFilozof** [comment]
- [ ] `== operator`
- [ ] `%has% operator`
- [ ] `find_motifs`
- [ ] `encode`
- [ ] `typify`
- [ ] `substitute_letters`
- [ ] `write_fasta`
- [ ] `reverse`
- [ ] `bite`
- [ ] `remove_ambiguous` (old `clean`)
- [ ] `complement`
- [ ] `find_invalid_letters`
- [ ] `translate`
