### ISSUE TITLE
Cover more complicated cases of multichar alphabets packing of strings

### ISSUE THREAD

**Issue by DominikRafacz** [BioGenies/tidysq#70]
Currently `ProtoSequenceInputInterpreter` reads elements from `ProtoSequence<STRING_PT>` greedily. That means: if there are letters "A" and "AA" in the alphabet (which is some kind of extremely edge case, but we don't want to omit such!) and sequences would be read like:
* "AX" ->  "A", "X"
* "AAX" -> "AA", "X"
* "AAAX" -> "AA", "A", "X"

All unmatched subpatterns are treated as NA values and during letter matching, after hitting the char that does not have a corresponding letter in the parsing tree, all characters that were matched for a current letter so far are discarded, the result of reading is NA value and the further character begins reading a new letter. So, if "AA" is present in the alphabet, but "A" is not:
* "AX" -> NA, "X"
* "AAX" -> "AA", "X"
* "AAAX" -> "AA", NA, "X"

These two behaviors combined result in another edge case (even edgier, I mean - that's almost surreal...). Suppose we have "A" and "AAA" letters, but we do not have "AA". For earlier examples:
* "AX" -> "A", "X"
* "AAX" -> NA, "X"
* "AAAX" -> "AAA",  "X"

but it seems that the second case should be parsed as "A", "A", "X". 

At the moment we will not focus on covering such wild cases, but it is worth having it in mind.

**Comment by MatiFilozof** [comment]
Managed to replace this problem with failing to execute when `NA` appears (so examples 4 & 6). Not exactly an improvement, but should be easier to track down now that we know it fails somewhere in the newly written `LetterTree` and `LetterNode` classes.
