### ISSUE TITLE
Add human readable alias and blossum matrix

### ISSUE THREAD

**Issue by michbur** [BioGenies/tidysq#9]
What are suitable human-readable names?

**Comment by leonjessen** [comment]
So, what I am thinking is e.g.:

```{r}
my_data %>% mutate(sq_enc = sq %>% encode(encoding = "BLOSUM62"))
```

and then exchange the `encoding` argument with e.g. `"BLOSUM50"`, `"Atchley"`, `"Hydropathy"`, etc.

Also, as we talked about, we could choose to nest the encoding in the tibble to keep everything connected and then e.g. augment with a `as_keras_tensor()` function, which extracts the nested encodings and converts them to format and dimensions used by `keras`?

**Comment by MatiFilozof** [comment]
This functionality is a great idea, but this is too much for the scope of this project. `tidysq` is meant to be lightweight, so this could be implemented in a separate package that extends `tidysq`.
